Name: kits
Main: XoticRealmsOwnerandDev\Simplekits\Main
Aurthor: XoticRealmsOwnerandDev & Blubberboy333
Version: 1.0
API: [2.0.0]
Description: gives a player a kit when they use the command

Commands:
      kit: 
       usage: /kit <KitName | list>
       description: gives a player a kit
       permission: kit.use
permissions:
      kit:
            default: false
            description: Allows the player to use all of the SimpleKits features
            children:
                  kit.use:
                        default: op
                        description: Allows the player to use the kit command
