Name: kits
Main: XoticRealmsOwnerandDev\kits\kits.php
Aurthor: XoticRealmsOwnerandDev
Version: 1.0
API: [2.0.0]
Description: gives a player a kit when they dev the command

Commands:
      kit: 
       usage: /kit <kit name>
       description: gives a player a kit
       permission: kit.use
permissions:
           Kit: kit.use.<kit name>
               default:
               description:
