# Commands to run when a player puts on a new kit
# {PLAYER} for the player
# {NAME} for the player's name
Commands:
- tell {PLAYER} thank you for using your kit

# List of kit names
List: ["Default", "OP"]

Default:
#Items that are in the kit
  - 299
  - 300
  - 297
OP:
  - 310
  - 311
  - 312
  - 313
  - 276
