# Commands to run when a player puts on a new kit
# {PLAYER} for the player
# {NAME} for the player's name
Commands:
- tell {PLAYER} thank you for using your kit

# List of kit names
List: ["Default", "OP"]

# The kit below is the default format. You can add and remove kits if you'd like to
#KitName: Description
Default: Default kit
#Items that are in the kit
  - 299 [enchantment id] [enchantment level]
  - 300 [enchantment id] [enchantment level]
  - 297 [enchantment id] [enchantment level]
  
OP: Over Powered kit
  - 310 [enchantment id] [enchantment level]
  - 311 [enchantment id] [enchantment level]
  - 312 [enchantment id] [enchantment level]
  - 313 [enchantment id] [enchantment level]
  - 276 [enchantment id] [enchantment level]
